TABLE_WIDTH = 5
TABLE_HEIGHT = 5

STEP = 1
DIRECTION_LIST = ['NORTH','EAST','SOUTH','WEST']

DIRECTION_RELATED_COORDINATION = {
    'NORTH':['Y',STEP],
    'EAST':['X',STEP],
    'SOUTH':['Y',-1* STEP],
    'WEST':['X',-1 *STEP]
}
